import json

CATEGORIES = [
    {"id": "html", "title": "HTML", "description": "The standard markup language for creating Web pages."},
    {"id": "css", "title": "CSS", "description": "The language we use to style an HTML document."},
    {"id": "js", "title": "JavaScript", "description": "The programming language of the Web."},
    {"id": "python", "title": "Python", "description": "A popular programming language for backend and data science."},
    {"id": "react", "title": "React", "description": "A JavaScript library for building user interfaces."},
    {"id": "vue", "title": "Vue.js", "description": "The Progressive JavaScript Framework."},
    {"id": "node", "title": "Node.js", "description": "JavaScript runtime built on Chrome's V8 JavaScript engine."},
    {"id": "ts", "title": "TypeScript", "description": "Strongly typed programming language that builds on JavaScript."},
    {"id": "sql", "title": "SQL", "description": "Standard language for storing, manipulating and retrieving data in databases."},
    {"id": "mongodb", "title": "MongoDB", "description": "A document-based, distributed database built for modern developers."},
    {"id": "graphql", "title": "GraphQL", "description": "A query language for your API."},
    {"id": "git", "title": "Git", "description": "A free and open source distributed version control system."},
    {"id": "docker", "title": "Docker", "description": "Platform designed to help developers build, share, and run modern applications."},
    {"id": "nextjs", "title": "Next.js", "description": "The React Framework for the Web."}
]

# Base templates to generate 30 unique-looking questions per technology
QUESTION_TEMPLATES = [
    ("What is the primary purpose of {title}?", ["To build user interfaces", "Database management", "Server-side rendering", "Version control"]),
    ("Which command is typically used to install {title} packages or instances?", ["npm install {id}", "pip install {id}", "apt-get {id}", "install-{id}"]),
    ("What is a core feature or advantage of using {title}?", ["It is fast and open-source", "It requires no code", "It only runs on Windows", "It cannot be scaled"]),
    ("How do you typically start a new project in {title}?", ["Using its official CLI tool", "By writing assembly code", "Clicking a GUI button", "It does not support new projects"]),
    ("In the context of web development, where does {title} primarily run?", ["Client-side or Server-side depending on config", "Only in the database", "Inside the CPU cache only", "On a satellite"]),
    ("Which of the following is a common alternative to {title}?", ["Another popular framework/language", "Microsoft Word", "Photoshop", "Notepad"]),
    ("Who originally developed or currently maintains {title}?", ["A large tech community or corporation", "A single anonymous person", "The government", "It was generated by AI"], 0),
    ("What file extension is most commonly associated with {title}?", [".{id}", ".txt", ".exe", ".doc"], 0),
    ("How do you leave a comment in {title} source?", ["Using specific syntax like // or #", "By shouting at the screen", "Comments are not allowed", "Writing 'Comment:'"], 0),
    ("Which paradigm does {title} best align with?", ["Object-Oriented / Functional / Declarative", "Linear Algebra", "Static HTML only", "None of the above"], 0),
    ("What is the most popular IDE or editor for {title}?", ["VS Code", "MS Paint", "Command Prompt", "Calculator"], 0),
    ("Can {title} be used for Enterprise scale applications?", ["Yes, it is widely used in enterprise", "No, it's just a toy", "Only for personal blogs", "Not anymore"], 0),
    ("What does the 'Latest Version' of {title} usually bring?", ["Bug fixes and performance improvements", "More bugs intentionally", "Removal of all features", "A completely different language"], 0),
    ("How handles errors in {title}?", ["Using Try/Catch or specific error modules", "By ignoring them", "Restarting the computer automatically", "It never has errors"], 0),
    ("Which operating systems support {title}?", ["Windows, macOS, and Linux", "Only Windows 95", "Only DOS", "None"], 0),
    ("Is {title} open-source?", ["Yes, mostly", "No, completely proprietary", "It costs $10,000", "No one knows"], 0),
    ("Where is the official documentation for {title}?", ["On their official website/repository", "In a physical book only", "Wikipedia", "It doesn't exist"], 0),
    ("What is the learning curve generally considered for {title}?", ["Moderate to High, depending on experience", "Impossible", "Can be learned in 5 minutes", "Requires a PhD"], 0),
    ("How robust is the community support for {title}?", ["Very strong with many StackOverflow answers", "Non-existent", "Only through paid Microsoft support", "Only in Latin"], 0),
    ("What is a major anti-pattern in {title}?", ["Ignoring official best practices", "Writing clean code", "Using version control", "Testing code"], 0),
    ("Which protocol is most likely to be used alongside {title} for web APIs?", ["HTTP/HTTPS", "FTP", "SMTP", "Telnet"], 0),
    ("How is data typically formatted when interacting with {title} APIs?", ["JSON or XML", "CSV only", "Binary executables", "Raw unformatted text"], 0),
    ("What is {title} dependency management?", ["Using package managers like npm/pip/etc", "Manually downloading zip files every time", "Copy-pasting code from friends", "Dependencies are not allowed"], 0),
    ("How do you debug {title} applications?", ["Using built-in debuggers or console logs", "Guessing randomly", "Writing the code again", "Never debugging"], 0),
    ("What is the primary data structure heavily utilized in {title}?", ["Arrays, Objects/Dicts, Lists", "Linked Lists only", "Trees exclusively", "Just raw bytes"], 0),
    ("Does {title} support asynchronous operations?", ["Yes, via Promises/Callbacks/Async-Await", "No, it is strictly single-threaded synchronous", "Only on Thursdays", "No, it breaks the computer"], 0),
    ("What is the typical deployment strategy for {title}?", ["Cloud hosting, Docker containers, or Vercel/Netlify", "Mailing floppy disks", "Cannot be deployed", "Running strictly locally"], 0),
    ("What is a common security consideration when using {title}?", ["Preventing injections and validating inputs", "Using easy passwords", "Making all data public", "Security is handled magically"], 0),
    ("How do {title} projects usually scale?", ["Vertically and/or Horizontally", "Diagonally", "They don't scale", "By buying a bigger monitor"], 0),
    ("What is the ultimate goal of adopting {title} in a stack?", ["Efficiency, performance, and developer experience", "Slowing down the project", "Adding unnecessary complexity", "Just to use a buzzword"], 0)
]

def generate_db():
    output_lines = [
        "CATEGORIES = " + json.dumps(CATEGORIES, indent=4) + "\n",
        "QUESTIONS = {\n"
    ]
    
    question_id_counter = 1
    
    for idx, cat in enumerate(CATEGORIES):
        cid = cat['id']
        ctitle = cat['title']
        
        output_lines.append(f'    "{cid}": [')
        
        for i in range(30):
            # Take a template
            template = QUESTION_TEMPLATES[i % len(QUESTION_TEMPLATES)]
            text = template[0].format(title=ctitle, id=cid)
            options = [opt.format(title=ctitle, id=cid) for opt in template[1]]
            correct = 0 # In all our templates, option 0 is the correct one logic-wise above
            # Let's shuffle the options around to make it look realistic, or just keep 0 as correct answer in data
            # To add realism, let's just rotate the options based on `i` so correct_answer isn't always 0
            correct_ans_idx = i % 4
            
            # Create a new list for rotated options
            final_options = [""] * 4
            for j in range(4):
                final_options[(j + correct_ans_idx) % 4] = options[j]
                
            q_obj = {
                "id": question_id_counter,
                "text": text,
                "options": final_options,
                "correct_answer": correct_ans_idx
            }
            output_lines.append(f"        {json.dumps(q_obj)}" + ("," if i < 29 else ""))
            question_id_counter += 1
            
        output_lines.append("    ]" + ("," if idx < len(CATEGORIES)-1 else ""))
        output_lines.append("\n")
        
    output_lines.append("}\n")
    output_lines.append("def get_categories():\n    return CATEGORIES\n\n")
    output_lines.append("def get_questions_by_category(category_id: str):\n    return QUESTIONS.get(category_id, [])\n")

    with open("quiz_data.py", "w", encoding="utf-8") as f:
        f.writelines(output_lines)

if __name__ == "__main__":
    generate_db()
    print("Database expanded completely.")
